version: '3'
services:
  app:
    container_name: pizza-ecommerce
    restart: unless-stopped
    build: .
    volumes:
      - pizza-ecommerce-db:/opt/pizza-ecommerce/.data
      - public:/opt/pizza-ecommerce/public

  webserver:
    container_name: webserver
    restart: unless-stopped
    image: nginx:mainline-alpine
    ports:
      - 80:80
    volumes:
    - ./nginx-conf:/etc/nginx/conf.d
    - public:/var/www/public
    depends_on:
      - app

volumes:
  public:
  pizza-ecommerce-db: